// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package edu.usfca.protobuf;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.usfca.protobuf.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>optional string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <pre>
     * Which page number do we want?
     * </pre>
     *
     * <code>optional int32 page_number = 2;</code>
     */
    int getPageNumber();

    /**
     * <pre>
     * Number of results to return per page.
     * </pre>
     *
     * <code>optional int32 result_per_page = 3;</code>
     */
    int getResultPerPage();
  }
  /**
   * <pre>
   * test code for lecture.
   * https://developers.google.com/protocol-buffers/docs/proto3
   * </pre>
   *
   * Protobuf type {@code edu.usfca.protobuf.SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.usfca.protobuf.SearchRequest)
      SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      query_ = "";
      pageNumber_ = 0;
      resultPerPage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 16: {

              pageNumber_ = input.readInt32();
              break;
            }
            case 24: {

              resultPerPage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.protobuf.Common.SearchRequest.class, edu.usfca.protobuf.Common.SearchRequest.Builder.class);
    }

    public interface NestedOrBuilder extends
        // @@protoc_insertion_point(interface_extends:edu.usfca.protobuf.SearchRequest.Nested)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string some_id = 1;</code>
       */
      java.lang.String getSomeId();
      /**
       * <code>optional string some_id = 1;</code>
       */
      com.google.protobuf.ByteString
          getSomeIdBytes();

      /**
       * <code>optional int64 some_value = 2;</code>
       */
      long getSomeValue();

      /**
       * <code>repeated string some_data = 3;</code>
       */
      java.util.List<java.lang.String>
          getSomeDataList();
      /**
       * <code>repeated string some_data = 3;</code>
       */
      int getSomeDataCount();
      /**
       * <code>repeated string some_data = 3;</code>
       */
      java.lang.String getSomeData(int index);
      /**
       * <code>repeated string some_data = 3;</code>
       */
      com.google.protobuf.ByteString
          getSomeDataBytes(int index);

      /**
       * <code>optional string even_more_data = 4;</code>
       */
      java.lang.String getEvenMoreData();
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      com.google.protobuf.ByteString
          getEvenMoreDataBytes();

      /**
       * <code>optional int64 even_more_value = 5;</code>
       */
      long getEvenMoreValue();
    }
    /**
     * Protobuf type {@code edu.usfca.protobuf.SearchRequest.Nested}
     */
    public  static final class Nested extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:edu.usfca.protobuf.SearchRequest.Nested)
        NestedOrBuilder {
      // Use Nested.newBuilder() to construct.
      private Nested(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Nested() {
        someId_ = "";
        someValue_ = 0L;
        someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        evenMoreData_ = "";
        evenMoreValue_ = 0L;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Nested(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                someId_ = s;
                break;
              }
              case 16: {

                someValue_ = input.readInt64();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  someData_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                someData_.add(s);
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                evenMoreData_ = s;
                break;
              }
              case 40: {

                evenMoreValue_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            someData_ = someData_.getUnmodifiableView();
          }
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_Nested_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.protobuf.Common.SearchRequest.Nested.class, edu.usfca.protobuf.Common.SearchRequest.Nested.Builder.class);
      }

      private int bitField0_;
      public static final int SOME_ID_FIELD_NUMBER = 1;
      private volatile java.lang.Object someId_;
      /**
       * <code>optional string some_id = 1;</code>
       */
      public java.lang.String getSomeId() {
        java.lang.Object ref = someId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someId_ = s;
          return s;
        }
      }
      /**
       * <code>optional string some_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSomeIdBytes() {
        java.lang.Object ref = someId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SOME_VALUE_FIELD_NUMBER = 2;
      private long someValue_;
      /**
       * <code>optional int64 some_value = 2;</code>
       */
      public long getSomeValue() {
        return someValue_;
      }

      public static final int SOME_DATA_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList someData_;
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSomeDataList() {
        return someData_;
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public int getSomeDataCount() {
        return someData_.size();
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public java.lang.String getSomeData(int index) {
        return someData_.get(index);
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSomeDataBytes(int index) {
        return someData_.getByteString(index);
      }

      public static final int EVEN_MORE_DATA_FIELD_NUMBER = 4;
      private volatile java.lang.Object evenMoreData_;
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public java.lang.String getEvenMoreData() {
        java.lang.Object ref = evenMoreData_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          evenMoreData_ = s;
          return s;
        }
      }
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEvenMoreDataBytes() {
        java.lang.Object ref = evenMoreData_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          evenMoreData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EVEN_MORE_VALUE_FIELD_NUMBER = 5;
      private long evenMoreValue_;
      /**
       * <code>optional int64 even_more_value = 5;</code>
       */
      public long getEvenMoreValue() {
        return evenMoreValue_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getSomeIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, someId_);
        }
        if (someValue_ != 0L) {
          output.writeInt64(2, someValue_);
        }
        for (int i = 0; i < someData_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, someData_.getRaw(i));
        }
        if (!getEvenMoreDataBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, evenMoreData_);
        }
        if (evenMoreValue_ != 0L) {
          output.writeInt64(5, evenMoreValue_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getSomeIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, someId_);
        }
        if (someValue_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, someValue_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < someData_.size(); i++) {
            dataSize += computeStringSizeNoTag(someData_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getSomeDataList().size();
        }
        if (!getEvenMoreDataBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, evenMoreData_);
        }
        if (evenMoreValue_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, evenMoreValue_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof edu.usfca.protobuf.Common.SearchRequest.Nested)) {
          return super.equals(obj);
        }
        edu.usfca.protobuf.Common.SearchRequest.Nested other = (edu.usfca.protobuf.Common.SearchRequest.Nested) obj;

        boolean result = true;
        result = result && getSomeId()
            .equals(other.getSomeId());
        result = result && (getSomeValue()
            == other.getSomeValue());
        result = result && getSomeDataList()
            .equals(other.getSomeDataList());
        result = result && getEvenMoreData()
            .equals(other.getEvenMoreData());
        result = result && (getEvenMoreValue()
            == other.getEvenMoreValue());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + SOME_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSomeId().hashCode();
        hash = (37 * hash) + SOME_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSomeValue());
        if (getSomeDataCount() > 0) {
          hash = (37 * hash) + SOME_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getSomeDataList().hashCode();
        }
        hash = (37 * hash) + EVEN_MORE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getEvenMoreData().hashCode();
        hash = (37 * hash) + EVEN_MORE_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEvenMoreValue());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static edu.usfca.protobuf.Common.SearchRequest.Nested parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(edu.usfca.protobuf.Common.SearchRequest.Nested prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code edu.usfca.protobuf.SearchRequest.Nested}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:edu.usfca.protobuf.SearchRequest.Nested)
          edu.usfca.protobuf.Common.SearchRequest.NestedOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_Nested_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  edu.usfca.protobuf.Common.SearchRequest.Nested.class, edu.usfca.protobuf.Common.SearchRequest.Nested.Builder.class);
        }

        // Construct using edu.usfca.protobuf.Common.SearchRequest.Nested.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          someId_ = "";

          someValue_ = 0L;

          someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          evenMoreData_ = "";

          evenMoreValue_ = 0L;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor;
        }

        public edu.usfca.protobuf.Common.SearchRequest.Nested getDefaultInstanceForType() {
          return edu.usfca.protobuf.Common.SearchRequest.Nested.getDefaultInstance();
        }

        public edu.usfca.protobuf.Common.SearchRequest.Nested build() {
          edu.usfca.protobuf.Common.SearchRequest.Nested result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public edu.usfca.protobuf.Common.SearchRequest.Nested buildPartial() {
          edu.usfca.protobuf.Common.SearchRequest.Nested result = new edu.usfca.protobuf.Common.SearchRequest.Nested(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.someId_ = someId_;
          result.someValue_ = someValue_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            someData_ = someData_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.someData_ = someData_;
          result.evenMoreData_ = evenMoreData_;
          result.evenMoreValue_ = evenMoreValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof edu.usfca.protobuf.Common.SearchRequest.Nested) {
            return mergeFrom((edu.usfca.protobuf.Common.SearchRequest.Nested)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(edu.usfca.protobuf.Common.SearchRequest.Nested other) {
          if (other == edu.usfca.protobuf.Common.SearchRequest.Nested.getDefaultInstance()) return this;
          if (!other.getSomeId().isEmpty()) {
            someId_ = other.someId_;
            onChanged();
          }
          if (other.getSomeValue() != 0L) {
            setSomeValue(other.getSomeValue());
          }
          if (!other.someData_.isEmpty()) {
            if (someData_.isEmpty()) {
              someData_ = other.someData_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSomeDataIsMutable();
              someData_.addAll(other.someData_);
            }
            onChanged();
          }
          if (!other.getEvenMoreData().isEmpty()) {
            evenMoreData_ = other.evenMoreData_;
            onChanged();
          }
          if (other.getEvenMoreValue() != 0L) {
            setEvenMoreValue(other.getEvenMoreValue());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          edu.usfca.protobuf.Common.SearchRequest.Nested parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (edu.usfca.protobuf.Common.SearchRequest.Nested) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object someId_ = "";
        /**
         * <code>optional string some_id = 1;</code>
         */
        public java.lang.String getSomeId() {
          java.lang.Object ref = someId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            someId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string some_id = 1;</code>
         */
        public com.google.protobuf.ByteString
            getSomeIdBytes() {
          java.lang.Object ref = someId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            someId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string some_id = 1;</code>
         */
        public Builder setSomeId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          someId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string some_id = 1;</code>
         */
        public Builder clearSomeId() {
          
          someId_ = getDefaultInstance().getSomeId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string some_id = 1;</code>
         */
        public Builder setSomeIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          someId_ = value;
          onChanged();
          return this;
        }

        private long someValue_ ;
        /**
         * <code>optional int64 some_value = 2;</code>
         */
        public long getSomeValue() {
          return someValue_;
        }
        /**
         * <code>optional int64 some_value = 2;</code>
         */
        public Builder setSomeValue(long value) {
          
          someValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 some_value = 2;</code>
         */
        public Builder clearSomeValue() {
          
          someValue_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureSomeDataIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            someData_ = new com.google.protobuf.LazyStringArrayList(someData_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getSomeDataList() {
          return someData_.getUnmodifiableView();
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public int getSomeDataCount() {
          return someData_.size();
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public java.lang.String getSomeData(int index) {
          return someData_.get(index);
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public com.google.protobuf.ByteString
            getSomeDataBytes(int index) {
          return someData_.getByteString(index);
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public Builder setSomeData(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSomeDataIsMutable();
          someData_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public Builder addSomeData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureSomeDataIsMutable();
          someData_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public Builder addAllSomeData(
            java.lang.Iterable<java.lang.String> values) {
          ensureSomeDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, someData_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public Builder clearSomeData() {
          someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string some_data = 3;</code>
         */
        public Builder addSomeDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureSomeDataIsMutable();
          someData_.add(value);
          onChanged();
          return this;
        }

        private java.lang.Object evenMoreData_ = "";
        /**
         * <code>optional string even_more_data = 4;</code>
         */
        public java.lang.String getEvenMoreData() {
          java.lang.Object ref = evenMoreData_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            evenMoreData_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string even_more_data = 4;</code>
         */
        public com.google.protobuf.ByteString
            getEvenMoreDataBytes() {
          java.lang.Object ref = evenMoreData_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            evenMoreData_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string even_more_data = 4;</code>
         */
        public Builder setEvenMoreData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          evenMoreData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string even_more_data = 4;</code>
         */
        public Builder clearEvenMoreData() {
          
          evenMoreData_ = getDefaultInstance().getEvenMoreData();
          onChanged();
          return this;
        }
        /**
         * <code>optional string even_more_data = 4;</code>
         */
        public Builder setEvenMoreDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          evenMoreData_ = value;
          onChanged();
          return this;
        }

        private long evenMoreValue_ ;
        /**
         * <code>optional int64 even_more_value = 5;</code>
         */
        public long getEvenMoreValue() {
          return evenMoreValue_;
        }
        /**
         * <code>optional int64 even_more_value = 5;</code>
         */
        public Builder setEvenMoreValue(long value) {
          
          evenMoreValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 even_more_value = 5;</code>
         */
        public Builder clearEvenMoreValue() {
          
          evenMoreValue_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:edu.usfca.protobuf.SearchRequest.Nested)
      }

      // @@protoc_insertion_point(class_scope:edu.usfca.protobuf.SearchRequest.Nested)
      private static final edu.usfca.protobuf.Common.SearchRequest.Nested DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new edu.usfca.protobuf.Common.SearchRequest.Nested();
      }

      public static edu.usfca.protobuf.Common.SearchRequest.Nested getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Nested>
          PARSER = new com.google.protobuf.AbstractParser<Nested>() {
        public Nested parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Nested(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Nested> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Nested> getParserForType() {
        return PARSER;
      }

      public edu.usfca.protobuf.Common.SearchRequest.Nested getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>optional string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>optional string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <pre>
     * Which page number do we want?
     * </pre>
     *
     * <code>optional int32 page_number = 2;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
    private int resultPerPage_;
    /**
     * <pre>
     * Number of results to return per page.
     * </pre>
     *
     * <code>optional int32 result_per_page = 3;</code>
     */
    public int getResultPerPage() {
      return resultPerPage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (pageNumber_ != 0) {
        output.writeInt32(2, pageNumber_);
      }
      if (resultPerPage_ != 0) {
        output.writeInt32(3, resultPerPage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (pageNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      if (resultPerPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resultPerPage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.protobuf.Common.SearchRequest)) {
        return super.equals(obj);
      }
      edu.usfca.protobuf.Common.SearchRequest other = (edu.usfca.protobuf.Common.SearchRequest) obj;

      boolean result = true;
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && (getPageNumber()
          == other.getPageNumber());
      result = result && (getResultPerPage()
          == other.getResultPerPage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPageNumber();
      hash = (37 * hash) + RESULT_PER_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResultPerPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.protobuf.Common.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * test code for lecture.
     * https://developers.google.com/protocol-buffers/docs/proto3
     * </pre>
     *
     * Protobuf type {@code edu.usfca.protobuf.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.usfca.protobuf.SearchRequest)
        edu.usfca.protobuf.Common.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.protobuf.Common.SearchRequest.class, edu.usfca.protobuf.Common.SearchRequest.Builder.class);
      }

      // Construct using edu.usfca.protobuf.Common.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        query_ = "";

        pageNumber_ = 0;

        resultPerPage_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_SearchRequest_descriptor;
      }

      public edu.usfca.protobuf.Common.SearchRequest getDefaultInstanceForType() {
        return edu.usfca.protobuf.Common.SearchRequest.getDefaultInstance();
      }

      public edu.usfca.protobuf.Common.SearchRequest build() {
        edu.usfca.protobuf.Common.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.protobuf.Common.SearchRequest buildPartial() {
        edu.usfca.protobuf.Common.SearchRequest result = new edu.usfca.protobuf.Common.SearchRequest(this);
        result.query_ = query_;
        result.pageNumber_ = pageNumber_;
        result.resultPerPage_ = resultPerPage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.protobuf.Common.SearchRequest) {
          return mergeFrom((edu.usfca.protobuf.Common.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.protobuf.Common.SearchRequest other) {
        if (other == edu.usfca.protobuf.Common.SearchRequest.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        if (other.getPageNumber() != 0) {
          setPageNumber(other.getPageNumber());
        }
        if (other.getResultPerPage() != 0) {
          setResultPerPage(other.getResultPerPage());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.protobuf.Common.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.protobuf.Common.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object query_ = "";
      /**
       * <code>optional string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <pre>
       * Which page number do we want?
       * </pre>
       *
       * <code>optional int32 page_number = 2;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <pre>
       * Which page number do we want?
       * </pre>
       *
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder setPageNumber(int value) {
        
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Which page number do we want?
       * </pre>
       *
       * <code>optional int32 page_number = 2;</code>
       */
      public Builder clearPageNumber() {
        
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      private int resultPerPage_ ;
      /**
       * <pre>
       * Number of results to return per page.
       * </pre>
       *
       * <code>optional int32 result_per_page = 3;</code>
       */
      public int getResultPerPage() {
        return resultPerPage_;
      }
      /**
       * <pre>
       * Number of results to return per page.
       * </pre>
       *
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder setResultPerPage(int value) {
        
        resultPerPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of results to return per page.
       * </pre>
       *
       * <code>optional int32 result_per_page = 3;</code>
       */
      public Builder clearResultPerPage() {
        
        resultPerPage_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.usfca.protobuf.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:edu.usfca.protobuf.SearchRequest)
    private static final edu.usfca.protobuf.Common.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.protobuf.Common.SearchRequest();
    }

    public static edu.usfca.protobuf.Common.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    public edu.usfca.protobuf.Common.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NotNestedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.usfca.protobuf.NotNested)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string some_id = 1;</code>
     */
    java.lang.String getSomeId();
    /**
     * <code>optional string some_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSomeIdBytes();

    /**
     * <code>optional int64 some_value = 2;</code>
     */
    long getSomeValue();

    /**
     * <code>repeated string some_data = 3;</code>
     */
    java.util.List<java.lang.String>
        getSomeDataList();
    /**
     * <code>repeated string some_data = 3;</code>
     */
    int getSomeDataCount();
    /**
     * <code>repeated string some_data = 3;</code>
     */
    java.lang.String getSomeData(int index);
    /**
     * <code>repeated string some_data = 3;</code>
     */
    com.google.protobuf.ByteString
        getSomeDataBytes(int index);

    /**
     * <code>optional string even_more_data = 4;</code>
     */
    java.lang.String getEvenMoreData();
    /**
     * <code>optional string even_more_data = 4;</code>
     */
    com.google.protobuf.ByteString
        getEvenMoreDataBytes();

    /**
     * <code>optional int64 even_more_value = 5;</code>
     */
    long getEvenMoreValue();
  }
  /**
   * Protobuf type {@code edu.usfca.protobuf.NotNested}
   */
  public  static final class NotNested extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.usfca.protobuf.NotNested)
      NotNestedOrBuilder {
    // Use NotNested.newBuilder() to construct.
    private NotNested(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotNested() {
      someId_ = "";
      someValue_ = 0L;
      someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      evenMoreData_ = "";
      evenMoreValue_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NotNested(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              someId_ = s;
              break;
            }
            case 16: {

              someValue_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                someData_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              someData_.add(s);
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              evenMoreData_ = s;
              break;
            }
            case 40: {

              evenMoreValue_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          someData_ = someData_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_NotNested_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_NotNested_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.protobuf.Common.NotNested.class, edu.usfca.protobuf.Common.NotNested.Builder.class);
    }

    private int bitField0_;
    public static final int SOME_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object someId_;
    /**
     * <code>optional string some_id = 1;</code>
     */
    public java.lang.String getSomeId() {
      java.lang.Object ref = someId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        someId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string some_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSomeIdBytes() {
      java.lang.Object ref = someId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOME_VALUE_FIELD_NUMBER = 2;
    private long someValue_;
    /**
     * <code>optional int64 some_value = 2;</code>
     */
    public long getSomeValue() {
      return someValue_;
    }

    public static final int SOME_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList someData_;
    /**
     * <code>repeated string some_data = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSomeDataList() {
      return someData_;
    }
    /**
     * <code>repeated string some_data = 3;</code>
     */
    public int getSomeDataCount() {
      return someData_.size();
    }
    /**
     * <code>repeated string some_data = 3;</code>
     */
    public java.lang.String getSomeData(int index) {
      return someData_.get(index);
    }
    /**
     * <code>repeated string some_data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSomeDataBytes(int index) {
      return someData_.getByteString(index);
    }

    public static final int EVEN_MORE_DATA_FIELD_NUMBER = 4;
    private volatile java.lang.Object evenMoreData_;
    /**
     * <code>optional string even_more_data = 4;</code>
     */
    public java.lang.String getEvenMoreData() {
      java.lang.Object ref = evenMoreData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evenMoreData_ = s;
        return s;
      }
    }
    /**
     * <code>optional string even_more_data = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEvenMoreDataBytes() {
      java.lang.Object ref = evenMoreData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evenMoreData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVEN_MORE_VALUE_FIELD_NUMBER = 5;
    private long evenMoreValue_;
    /**
     * <code>optional int64 even_more_value = 5;</code>
     */
    public long getEvenMoreValue() {
      return evenMoreValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSomeIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, someId_);
      }
      if (someValue_ != 0L) {
        output.writeInt64(2, someValue_);
      }
      for (int i = 0; i < someData_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, someData_.getRaw(i));
      }
      if (!getEvenMoreDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, evenMoreData_);
      }
      if (evenMoreValue_ != 0L) {
        output.writeInt64(5, evenMoreValue_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSomeIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, someId_);
      }
      if (someValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, someValue_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < someData_.size(); i++) {
          dataSize += computeStringSizeNoTag(someData_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSomeDataList().size();
      }
      if (!getEvenMoreDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, evenMoreData_);
      }
      if (evenMoreValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, evenMoreValue_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.protobuf.Common.NotNested)) {
        return super.equals(obj);
      }
      edu.usfca.protobuf.Common.NotNested other = (edu.usfca.protobuf.Common.NotNested) obj;

      boolean result = true;
      result = result && getSomeId()
          .equals(other.getSomeId());
      result = result && (getSomeValue()
          == other.getSomeValue());
      result = result && getSomeDataList()
          .equals(other.getSomeDataList());
      result = result && getEvenMoreData()
          .equals(other.getEvenMoreData());
      result = result && (getEvenMoreValue()
          == other.getEvenMoreValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SOME_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSomeId().hashCode();
      hash = (37 * hash) + SOME_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSomeValue());
      if (getSomeDataCount() > 0) {
        hash = (37 * hash) + SOME_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getSomeDataList().hashCode();
      }
      hash = (37 * hash) + EVEN_MORE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getEvenMoreData().hashCode();
      hash = (37 * hash) + EVEN_MORE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEvenMoreValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.NotNested parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.NotNested parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Common.NotNested parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.protobuf.Common.NotNested prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.usfca.protobuf.NotNested}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.usfca.protobuf.NotNested)
        edu.usfca.protobuf.Common.NotNestedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_NotNested_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_NotNested_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.protobuf.Common.NotNested.class, edu.usfca.protobuf.Common.NotNested.Builder.class);
      }

      // Construct using edu.usfca.protobuf.Common.NotNested.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        someId_ = "";

        someValue_ = 0L;

        someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        evenMoreData_ = "";

        evenMoreValue_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.protobuf.Common.internal_static_edu_usfca_protobuf_NotNested_descriptor;
      }

      public edu.usfca.protobuf.Common.NotNested getDefaultInstanceForType() {
        return edu.usfca.protobuf.Common.NotNested.getDefaultInstance();
      }

      public edu.usfca.protobuf.Common.NotNested build() {
        edu.usfca.protobuf.Common.NotNested result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.protobuf.Common.NotNested buildPartial() {
        edu.usfca.protobuf.Common.NotNested result = new edu.usfca.protobuf.Common.NotNested(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.someId_ = someId_;
        result.someValue_ = someValue_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          someData_ = someData_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.someData_ = someData_;
        result.evenMoreData_ = evenMoreData_;
        result.evenMoreValue_ = evenMoreValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.protobuf.Common.NotNested) {
          return mergeFrom((edu.usfca.protobuf.Common.NotNested)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.protobuf.Common.NotNested other) {
        if (other == edu.usfca.protobuf.Common.NotNested.getDefaultInstance()) return this;
        if (!other.getSomeId().isEmpty()) {
          someId_ = other.someId_;
          onChanged();
        }
        if (other.getSomeValue() != 0L) {
          setSomeValue(other.getSomeValue());
        }
        if (!other.someData_.isEmpty()) {
          if (someData_.isEmpty()) {
            someData_ = other.someData_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSomeDataIsMutable();
            someData_.addAll(other.someData_);
          }
          onChanged();
        }
        if (!other.getEvenMoreData().isEmpty()) {
          evenMoreData_ = other.evenMoreData_;
          onChanged();
        }
        if (other.getEvenMoreValue() != 0L) {
          setEvenMoreValue(other.getEvenMoreValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.protobuf.Common.NotNested parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.protobuf.Common.NotNested) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object someId_ = "";
      /**
       * <code>optional string some_id = 1;</code>
       */
      public java.lang.String getSomeId() {
        java.lang.Object ref = someId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string some_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSomeIdBytes() {
        java.lang.Object ref = someId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string some_id = 1;</code>
       */
      public Builder setSomeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string some_id = 1;</code>
       */
      public Builder clearSomeId() {
        
        someId_ = getDefaultInstance().getSomeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string some_id = 1;</code>
       */
      public Builder setSomeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        someId_ = value;
        onChanged();
        return this;
      }

      private long someValue_ ;
      /**
       * <code>optional int64 some_value = 2;</code>
       */
      public long getSomeValue() {
        return someValue_;
      }
      /**
       * <code>optional int64 some_value = 2;</code>
       */
      public Builder setSomeValue(long value) {
        
        someValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 some_value = 2;</code>
       */
      public Builder clearSomeValue() {
        
        someValue_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSomeDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          someData_ = new com.google.protobuf.LazyStringArrayList(someData_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSomeDataList() {
        return someData_.getUnmodifiableView();
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public int getSomeDataCount() {
        return someData_.size();
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public java.lang.String getSomeData(int index) {
        return someData_.get(index);
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSomeDataBytes(int index) {
        return someData_.getByteString(index);
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public Builder setSomeData(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSomeDataIsMutable();
        someData_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public Builder addSomeData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSomeDataIsMutable();
        someData_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public Builder addAllSomeData(
          java.lang.Iterable<java.lang.String> values) {
        ensureSomeDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, someData_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public Builder clearSomeData() {
        someData_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string some_data = 3;</code>
       */
      public Builder addSomeDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSomeDataIsMutable();
        someData_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object evenMoreData_ = "";
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public java.lang.String getEvenMoreData() {
        java.lang.Object ref = evenMoreData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          evenMoreData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEvenMoreDataBytes() {
        java.lang.Object ref = evenMoreData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          evenMoreData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public Builder setEvenMoreData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        evenMoreData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public Builder clearEvenMoreData() {
        
        evenMoreData_ = getDefaultInstance().getEvenMoreData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string even_more_data = 4;</code>
       */
      public Builder setEvenMoreDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        evenMoreData_ = value;
        onChanged();
        return this;
      }

      private long evenMoreValue_ ;
      /**
       * <code>optional int64 even_more_value = 5;</code>
       */
      public long getEvenMoreValue() {
        return evenMoreValue_;
      }
      /**
       * <code>optional int64 even_more_value = 5;</code>
       */
      public Builder setEvenMoreValue(long value) {
        
        evenMoreValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 even_more_value = 5;</code>
       */
      public Builder clearEvenMoreValue() {
        
        evenMoreValue_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.usfca.protobuf.NotNested)
    }

    // @@protoc_insertion_point(class_scope:edu.usfca.protobuf.NotNested)
    private static final edu.usfca.protobuf.Common.NotNested DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.protobuf.Common.NotNested();
    }

    public static edu.usfca.protobuf.Common.NotNested getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotNested>
        PARSER = new com.google.protobuf.AbstractParser<NotNested>() {
      public NotNested parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NotNested(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotNested> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NotNested> getParserForType() {
      return PARSER;
    }

    public edu.usfca.protobuf.Common.NotNested getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_SearchRequest_Nested_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_NotNested_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_NotNested_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\022edu.usfca.protobuf\"\277\001\n\rS" +
      "earchRequest\022\r\n\005query\030\001 \001(\t\022\023\n\013page_numb" +
      "er\030\002 \001(\005\022\027\n\017result_per_page\030\003 \001(\005\032q\n\006Nes" +
      "ted\022\017\n\007some_id\030\001 \001(\t\022\022\n\nsome_value\030\002 \001(\003" +
      "\022\021\n\tsome_data\030\003 \003(\t\022\026\n\016even_more_data\030\004 " +
      "\001(\t\022\027\n\017even_more_value\030\005 \001(\003\"t\n\tNotNeste" +
      "d\022\017\n\007some_id\030\001 \001(\t\022\022\n\nsome_value\030\002 \001(\003\022\021" +
      "\n\tsome_data\030\003 \003(\t\022\026\n\016even_more_data\030\004 \001(" +
      "\t\022\027\n\017even_more_value\030\005 \001(\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_edu_usfca_protobuf_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_usfca_protobuf_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_SearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "ResultPerPage", });
    internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor =
      internal_static_edu_usfca_protobuf_SearchRequest_descriptor.getNestedTypes().get(0);
    internal_static_edu_usfca_protobuf_SearchRequest_Nested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_SearchRequest_Nested_descriptor,
        new java.lang.String[] { "SomeId", "SomeValue", "SomeData", "EvenMoreData", "EvenMoreValue", });
    internal_static_edu_usfca_protobuf_NotNested_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_edu_usfca_protobuf_NotNested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_NotNested_descriptor,
        new java.lang.String[] { "SomeId", "SomeValue", "SomeData", "EvenMoreData", "EvenMoreValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
