// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bid.proto

package edu.usfca.protobuf;

public final class Bid {
  private Bid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code edu.usfca.protobuf.Exchange}
   */
  public enum Exchange
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_EXCHANGE = 0;</code>
     */
    UNKNOWN_EXCHANGE(0),
    /**
     * <code>ADX = 1;</code>
     */
    ADX(1),
    /**
     * <code>MOPUB = 2;</code>
     */
    MOPUB(2),
    /**
     * <code>UNITY = 3;</code>
     */
    UNITY(3),
    /**
     * <code>OPENX = 4;</code>
     */
    OPENX(4),
    /**
     * <code>VUNGLE = 5;</code>
     */
    VUNGLE(5),
    /**
     * <code>INMOBI = 6;</code>
     */
    INMOBI(6),
    /**
     * <code>FYBER = 7;</code>
     */
    FYBER(7),
    /**
     * <code>APPLOVIN = 8;</code>
     */
    APPLOVIN(8),
    /**
     * <code>ADCOLONY = 9;</code>
     */
    ADCOLONY(9),
    /**
     * <code>SMAATO = 10;</code>
     */
    SMAATO(10),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_EXCHANGE = 0;</code>
     */
    public static final int UNKNOWN_EXCHANGE_VALUE = 0;
    /**
     * <code>ADX = 1;</code>
     */
    public static final int ADX_VALUE = 1;
    /**
     * <code>MOPUB = 2;</code>
     */
    public static final int MOPUB_VALUE = 2;
    /**
     * <code>UNITY = 3;</code>
     */
    public static final int UNITY_VALUE = 3;
    /**
     * <code>OPENX = 4;</code>
     */
    public static final int OPENX_VALUE = 4;
    /**
     * <code>VUNGLE = 5;</code>
     */
    public static final int VUNGLE_VALUE = 5;
    /**
     * <code>INMOBI = 6;</code>
     */
    public static final int INMOBI_VALUE = 6;
    /**
     * <code>FYBER = 7;</code>
     */
    public static final int FYBER_VALUE = 7;
    /**
     * <code>APPLOVIN = 8;</code>
     */
    public static final int APPLOVIN_VALUE = 8;
    /**
     * <code>ADCOLONY = 9;</code>
     */
    public static final int ADCOLONY_VALUE = 9;
    /**
     * <code>SMAATO = 10;</code>
     */
    public static final int SMAATO_VALUE = 10;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Exchange valueOf(int value) {
      return forNumber(value);
    }

    public static Exchange forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_EXCHANGE;
        case 1: return ADX;
        case 2: return MOPUB;
        case 3: return UNITY;
        case 4: return OPENX;
        case 5: return VUNGLE;
        case 6: return INMOBI;
        case 7: return FYBER;
        case 8: return APPLOVIN;
        case 9: return ADCOLONY;
        case 10: return SMAATO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Exchange>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Exchange> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Exchange>() {
            public Exchange findValueByNumber(int number) {
              return Exchange.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return edu.usfca.protobuf.Bid.getDescriptor().getEnumTypes().get(0);
    }

    private static final Exchange[] VALUES = values();

    public static Exchange valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Exchange(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:edu.usfca.protobuf.Exchange)
  }

  public interface BidLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.usfca.protobuf.BidLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    boolean hasBidRequest();
    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    com.google.openrtb.OpenRtb.BidRequest getBidRequest();
    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidRequestOrBuilder();

    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
     */
    int getExchangeValue();
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
     */
    edu.usfca.protobuf.Bid.Exchange getExchange();

    /**
     * <pre>
     * received_at and processed_at are timestamps in (UNIX) millis in UTC.
     * received_at: When the request was received by our bid servers.
     * processed_at: When the request was processed by our bid servers.
     * </pre>
     *
     * <code>optional int64 received_at = 3;</code>
     */
    long getReceivedAt();

    /**
     * <code>optional int64 processed_at = 4;</code>
     */
    long getProcessedAt();

    /**
     * <pre>
     * Result code from bidder engine.
     * </pre>
     *
     * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
     */
    int getBidResultValue();
    /**
     * <pre>
     * Result code from bidder engine.
     * </pre>
     *
     * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
     */
    edu.usfca.protobuf.Bid.BidLog.BidResult getBidResult();

    /**
     * <pre>
     * This represents the (positive) price at which we bid (if we bid).
     * This should be 0 (default value) when bid_result is not "BID".
     * </pre>
     *
     * <code>optional int32 bid_price = 6;</code>
     */
    int getBidPrice();

    /**
     * <pre>
     * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
     * we may want to know which bid server caused such corrupted data.
     * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
     * </pre>
     *
     * <code>optional string bid_server = 7;</code>
     */
    java.lang.String getBidServer();
    /**
     * <pre>
     * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
     * we may want to know which bid server caused such corrupted data.
     * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
     * </pre>
     *
     * <code>optional string bid_server = 7;</code>
     */
    com.google.protobuf.ByteString
        getBidServerBytes();
  }
  /**
   * <pre>
   * This defines a log message that "our bidding servers" will create.
   * Each BidLog message contains the original BidRequest and other useful information.
   * Each BidRequest is expected to result in at most one BidLog from our servers (it could be "lossy").
   * </pre>
   *
   * Protobuf type {@code edu.usfca.protobuf.BidLog}
   */
  public  static final class BidLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.usfca.protobuf.BidLog)
      BidLogOrBuilder {
    // Use BidLog.newBuilder() to construct.
    private BidLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BidLog() {
      exchange_ = 0;
      receivedAt_ = 0L;
      processedAt_ = 0L;
      bidResult_ = 0;
      bidPrice_ = 0;
      bidServer_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BidLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (bidRequest_ != null) {
                subBuilder = bidRequest_.toBuilder();
              }
              bidRequest_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidRequest_);
                bidRequest_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              exchange_ = rawValue;
              break;
            }
            case 24: {

              receivedAt_ = input.readInt64();
              break;
            }
            case 32: {

              processedAt_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              bidResult_ = rawValue;
              break;
            }
            case 48: {

              bidPrice_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              bidServer_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.protobuf.Bid.internal_static_edu_usfca_protobuf_BidLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.protobuf.Bid.internal_static_edu_usfca_protobuf_BidLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.protobuf.Bid.BidLog.class, edu.usfca.protobuf.Bid.BidLog.Builder.class);
    }

    /**
     * Protobuf enum {@code edu.usfca.protobuf.BidLog.BidResult}
     */
    public enum BidResult
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_RESULT = 0;</code>
       */
      UNKNOWN_RESULT(0),
      /**
       * <code>BID = 1;</code>
       */
      BID(1),
      /**
       * <code>NO_CANDIDATE = 2;</code>
       */
      NO_CANDIDATE(2),
      /**
       * <code>INVALID_REQUEST = 3;</code>
       */
      INVALID_REQUEST(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN_RESULT = 0;</code>
       */
      public static final int UNKNOWN_RESULT_VALUE = 0;
      /**
       * <code>BID = 1;</code>
       */
      public static final int BID_VALUE = 1;
      /**
       * <code>NO_CANDIDATE = 2;</code>
       */
      public static final int NO_CANDIDATE_VALUE = 2;
      /**
       * <code>INVALID_REQUEST = 3;</code>
       */
      public static final int INVALID_REQUEST_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BidResult valueOf(int value) {
        return forNumber(value);
      }

      public static BidResult forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_RESULT;
          case 1: return BID;
          case 2: return NO_CANDIDATE;
          case 3: return INVALID_REQUEST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BidResult>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          BidResult> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BidResult>() {
              public BidResult findValueByNumber(int number) {
                return BidResult.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.usfca.protobuf.Bid.BidLog.getDescriptor().getEnumTypes().get(0);
      }

      private static final BidResult[] VALUES = values();

      public static BidResult valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private BidResult(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:edu.usfca.protobuf.BidLog.BidResult)
    }

    public static final int BID_REQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest bidRequest_;
    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    public boolean hasBidRequest() {
      return bidRequest_ != null;
    }
    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    public com.google.openrtb.OpenRtb.BidRequest getBidRequest() {
      return bidRequest_ == null ? com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance() : bidRequest_;
    }
    /**
     * <pre>
     * Original BidRequest proto.
     * </pre>
     *
     * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidRequestOrBuilder() {
      return getBidRequest();
    }

    public static final int EXCHANGE_FIELD_NUMBER = 2;
    private int exchange_;
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
     */
    public int getExchangeValue() {
      return exchange_;
    }
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
     */
    public edu.usfca.protobuf.Bid.Exchange getExchange() {
      edu.usfca.protobuf.Bid.Exchange result = edu.usfca.protobuf.Bid.Exchange.valueOf(exchange_);
      return result == null ? edu.usfca.protobuf.Bid.Exchange.UNRECOGNIZED : result;
    }

    public static final int RECEIVED_AT_FIELD_NUMBER = 3;
    private long receivedAt_;
    /**
     * <pre>
     * received_at and processed_at are timestamps in (UNIX) millis in UTC.
     * received_at: When the request was received by our bid servers.
     * processed_at: When the request was processed by our bid servers.
     * </pre>
     *
     * <code>optional int64 received_at = 3;</code>
     */
    public long getReceivedAt() {
      return receivedAt_;
    }

    public static final int PROCESSED_AT_FIELD_NUMBER = 4;
    private long processedAt_;
    /**
     * <code>optional int64 processed_at = 4;</code>
     */
    public long getProcessedAt() {
      return processedAt_;
    }

    public static final int BID_RESULT_FIELD_NUMBER = 5;
    private int bidResult_;
    /**
     * <pre>
     * Result code from bidder engine.
     * </pre>
     *
     * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
     */
    public int getBidResultValue() {
      return bidResult_;
    }
    /**
     * <pre>
     * Result code from bidder engine.
     * </pre>
     *
     * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
     */
    public edu.usfca.protobuf.Bid.BidLog.BidResult getBidResult() {
      edu.usfca.protobuf.Bid.BidLog.BidResult result = edu.usfca.protobuf.Bid.BidLog.BidResult.valueOf(bidResult_);
      return result == null ? edu.usfca.protobuf.Bid.BidLog.BidResult.UNRECOGNIZED : result;
    }

    public static final int BID_PRICE_FIELD_NUMBER = 6;
    private int bidPrice_;
    /**
     * <pre>
     * This represents the (positive) price at which we bid (if we bid).
     * This should be 0 (default value) when bid_result is not "BID".
     * </pre>
     *
     * <code>optional int32 bid_price = 6;</code>
     */
    public int getBidPrice() {
      return bidPrice_;
    }

    public static final int BID_SERVER_FIELD_NUMBER = 7;
    private volatile java.lang.Object bidServer_;
    /**
     * <pre>
     * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
     * we may want to know which bid server caused such corrupted data.
     * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
     * </pre>
     *
     * <code>optional string bid_server = 7;</code>
     */
    public java.lang.String getBidServer() {
      java.lang.Object ref = bidServer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bidServer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
     * we may want to know which bid server caused such corrupted data.
     * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
     * </pre>
     *
     * <code>optional string bid_server = 7;</code>
     */
    public com.google.protobuf.ByteString
        getBidServerBytes() {
      java.lang.Object ref = bidServer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidServer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasBidRequest()) {
        if (!getBidRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bidRequest_ != null) {
        output.writeMessage(1, getBidRequest());
      }
      if (exchange_ != edu.usfca.protobuf.Bid.Exchange.UNKNOWN_EXCHANGE.getNumber()) {
        output.writeEnum(2, exchange_);
      }
      if (receivedAt_ != 0L) {
        output.writeInt64(3, receivedAt_);
      }
      if (processedAt_ != 0L) {
        output.writeInt64(4, processedAt_);
      }
      if (bidResult_ != edu.usfca.protobuf.Bid.BidLog.BidResult.UNKNOWN_RESULT.getNumber()) {
        output.writeEnum(5, bidResult_);
      }
      if (bidPrice_ != 0) {
        output.writeInt32(6, bidPrice_);
      }
      if (!getBidServerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, bidServer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bidRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBidRequest());
      }
      if (exchange_ != edu.usfca.protobuf.Bid.Exchange.UNKNOWN_EXCHANGE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, exchange_);
      }
      if (receivedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, receivedAt_);
      }
      if (processedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, processedAt_);
      }
      if (bidResult_ != edu.usfca.protobuf.Bid.BidLog.BidResult.UNKNOWN_RESULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, bidResult_);
      }
      if (bidPrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, bidPrice_);
      }
      if (!getBidServerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, bidServer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.protobuf.Bid.BidLog)) {
        return super.equals(obj);
      }
      edu.usfca.protobuf.Bid.BidLog other = (edu.usfca.protobuf.Bid.BidLog) obj;

      boolean result = true;
      result = result && (hasBidRequest() == other.hasBidRequest());
      if (hasBidRequest()) {
        result = result && getBidRequest()
            .equals(other.getBidRequest());
      }
      result = result && exchange_ == other.exchange_;
      result = result && (getReceivedAt()
          == other.getReceivedAt());
      result = result && (getProcessedAt()
          == other.getProcessedAt());
      result = result && bidResult_ == other.bidResult_;
      result = result && (getBidPrice()
          == other.getBidPrice());
      result = result && getBidServer()
          .equals(other.getBidServer());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBidRequest()) {
        hash = (37 * hash) + BID_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getBidRequest().hashCode();
      }
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + exchange_;
      hash = (37 * hash) + RECEIVED_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceivedAt());
      hash = (37 * hash) + PROCESSED_AT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProcessedAt());
      hash = (37 * hash) + BID_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + bidResult_;
      hash = (37 * hash) + BID_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getBidPrice();
      hash = (37 * hash) + BID_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getBidServer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Bid.BidLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.protobuf.Bid.BidLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This defines a log message that "our bidding servers" will create.
     * Each BidLog message contains the original BidRequest and other useful information.
     * Each BidRequest is expected to result in at most one BidLog from our servers (it could be "lossy").
     * </pre>
     *
     * Protobuf type {@code edu.usfca.protobuf.BidLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.usfca.protobuf.BidLog)
        edu.usfca.protobuf.Bid.BidLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.protobuf.Bid.internal_static_edu_usfca_protobuf_BidLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.protobuf.Bid.internal_static_edu_usfca_protobuf_BidLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.protobuf.Bid.BidLog.class, edu.usfca.protobuf.Bid.BidLog.Builder.class);
      }

      // Construct using edu.usfca.protobuf.Bid.BidLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (bidRequestBuilder_ == null) {
          bidRequest_ = null;
        } else {
          bidRequest_ = null;
          bidRequestBuilder_ = null;
        }
        exchange_ = 0;

        receivedAt_ = 0L;

        processedAt_ = 0L;

        bidResult_ = 0;

        bidPrice_ = 0;

        bidServer_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.protobuf.Bid.internal_static_edu_usfca_protobuf_BidLog_descriptor;
      }

      public edu.usfca.protobuf.Bid.BidLog getDefaultInstanceForType() {
        return edu.usfca.protobuf.Bid.BidLog.getDefaultInstance();
      }

      public edu.usfca.protobuf.Bid.BidLog build() {
        edu.usfca.protobuf.Bid.BidLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.protobuf.Bid.BidLog buildPartial() {
        edu.usfca.protobuf.Bid.BidLog result = new edu.usfca.protobuf.Bid.BidLog(this);
        if (bidRequestBuilder_ == null) {
          result.bidRequest_ = bidRequest_;
        } else {
          result.bidRequest_ = bidRequestBuilder_.build();
        }
        result.exchange_ = exchange_;
        result.receivedAt_ = receivedAt_;
        result.processedAt_ = processedAt_;
        result.bidResult_ = bidResult_;
        result.bidPrice_ = bidPrice_;
        result.bidServer_ = bidServer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.protobuf.Bid.BidLog) {
          return mergeFrom((edu.usfca.protobuf.Bid.BidLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.protobuf.Bid.BidLog other) {
        if (other == edu.usfca.protobuf.Bid.BidLog.getDefaultInstance()) return this;
        if (other.hasBidRequest()) {
          mergeBidRequest(other.getBidRequest());
        }
        if (other.exchange_ != 0) {
          setExchangeValue(other.getExchangeValue());
        }
        if (other.getReceivedAt() != 0L) {
          setReceivedAt(other.getReceivedAt());
        }
        if (other.getProcessedAt() != 0L) {
          setProcessedAt(other.getProcessedAt());
        }
        if (other.bidResult_ != 0) {
          setBidResultValue(other.getBidResultValue());
        }
        if (other.getBidPrice() != 0) {
          setBidPrice(other.getBidPrice());
        }
        if (!other.getBidServer().isEmpty()) {
          bidServer_ = other.bidServer_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasBidRequest()) {
          if (!getBidRequest().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.protobuf.Bid.BidLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.protobuf.Bid.BidLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.openrtb.OpenRtb.BidRequest bidRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> bidRequestBuilder_;
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public boolean hasBidRequest() {
        return bidRequestBuilder_ != null || bidRequest_ != null;
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public com.google.openrtb.OpenRtb.BidRequest getBidRequest() {
        if (bidRequestBuilder_ == null) {
          return bidRequest_ == null ? com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance() : bidRequest_;
        } else {
          return bidRequestBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public Builder setBidRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidRequest_ = value;
          onChanged();
        } else {
          bidRequestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public Builder setBidRequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (bidRequestBuilder_ == null) {
          bidRequest_ = builderForValue.build();
          onChanged();
        } else {
          bidRequestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public Builder mergeBidRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidRequestBuilder_ == null) {
          if (bidRequest_ != null) {
            bidRequest_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(bidRequest_).mergeFrom(value).buildPartial();
          } else {
            bidRequest_ = value;
          }
          onChanged();
        } else {
          bidRequestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public Builder clearBidRequest() {
        if (bidRequestBuilder_ == null) {
          bidRequest_ = null;
          onChanged();
        } else {
          bidRequest_ = null;
          bidRequestBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getBidRequestBuilder() {
        
        onChanged();
        return getBidRequestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidRequestOrBuilder() {
        if (bidRequestBuilder_ != null) {
          return bidRequestBuilder_.getMessageOrBuilder();
        } else {
          return bidRequest_ == null ?
              com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance() : bidRequest_;
        }
      }
      /**
       * <pre>
       * Original BidRequest proto.
       * </pre>
       *
       * <code>optional .com.google.openrtb.BidRequest bid_request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getBidRequestFieldBuilder() {
        if (bidRequestBuilder_ == null) {
          bidRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getBidRequest(),
                  getParentForChildren(),
                  isClean());
          bidRequest_ = null;
        }
        return bidRequestBuilder_;
      }

      private int exchange_ = 0;
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
       */
      public int getExchangeValue() {
        return exchange_;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
       */
      public Builder setExchangeValue(int value) {
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
       */
      public edu.usfca.protobuf.Bid.Exchange getExchange() {
        edu.usfca.protobuf.Bid.Exchange result = edu.usfca.protobuf.Bid.Exchange.valueOf(exchange_);
        return result == null ? edu.usfca.protobuf.Bid.Exchange.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
       */
      public Builder setExchange(edu.usfca.protobuf.Bid.Exchange value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        exchange_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 2;</code>
       */
      public Builder clearExchange() {
        
        exchange_ = 0;
        onChanged();
        return this;
      }

      private long receivedAt_ ;
      /**
       * <pre>
       * received_at and processed_at are timestamps in (UNIX) millis in UTC.
       * received_at: When the request was received by our bid servers.
       * processed_at: When the request was processed by our bid servers.
       * </pre>
       *
       * <code>optional int64 received_at = 3;</code>
       */
      public long getReceivedAt() {
        return receivedAt_;
      }
      /**
       * <pre>
       * received_at and processed_at are timestamps in (UNIX) millis in UTC.
       * received_at: When the request was received by our bid servers.
       * processed_at: When the request was processed by our bid servers.
       * </pre>
       *
       * <code>optional int64 received_at = 3;</code>
       */
      public Builder setReceivedAt(long value) {
        
        receivedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * received_at and processed_at are timestamps in (UNIX) millis in UTC.
       * received_at: When the request was received by our bid servers.
       * processed_at: When the request was processed by our bid servers.
       * </pre>
       *
       * <code>optional int64 received_at = 3;</code>
       */
      public Builder clearReceivedAt() {
        
        receivedAt_ = 0L;
        onChanged();
        return this;
      }

      private long processedAt_ ;
      /**
       * <code>optional int64 processed_at = 4;</code>
       */
      public long getProcessedAt() {
        return processedAt_;
      }
      /**
       * <code>optional int64 processed_at = 4;</code>
       */
      public Builder setProcessedAt(long value) {
        
        processedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 processed_at = 4;</code>
       */
      public Builder clearProcessedAt() {
        
        processedAt_ = 0L;
        onChanged();
        return this;
      }

      private int bidResult_ = 0;
      /**
       * <pre>
       * Result code from bidder engine.
       * </pre>
       *
       * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
       */
      public int getBidResultValue() {
        return bidResult_;
      }
      /**
       * <pre>
       * Result code from bidder engine.
       * </pre>
       *
       * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
       */
      public Builder setBidResultValue(int value) {
        bidResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Result code from bidder engine.
       * </pre>
       *
       * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
       */
      public edu.usfca.protobuf.Bid.BidLog.BidResult getBidResult() {
        edu.usfca.protobuf.Bid.BidLog.BidResult result = edu.usfca.protobuf.Bid.BidLog.BidResult.valueOf(bidResult_);
        return result == null ? edu.usfca.protobuf.Bid.BidLog.BidResult.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Result code from bidder engine.
       * </pre>
       *
       * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
       */
      public Builder setBidResult(edu.usfca.protobuf.Bid.BidLog.BidResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        bidResult_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Result code from bidder engine.
       * </pre>
       *
       * <code>optional .edu.usfca.protobuf.BidLog.BidResult bid_result = 5;</code>
       */
      public Builder clearBidResult() {
        
        bidResult_ = 0;
        onChanged();
        return this;
      }

      private int bidPrice_ ;
      /**
       * <pre>
       * This represents the (positive) price at which we bid (if we bid).
       * This should be 0 (default value) when bid_result is not "BID".
       * </pre>
       *
       * <code>optional int32 bid_price = 6;</code>
       */
      public int getBidPrice() {
        return bidPrice_;
      }
      /**
       * <pre>
       * This represents the (positive) price at which we bid (if we bid).
       * This should be 0 (default value) when bid_result is not "BID".
       * </pre>
       *
       * <code>optional int32 bid_price = 6;</code>
       */
      public Builder setBidPrice(int value) {
        
        bidPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This represents the (positive) price at which we bid (if we bid).
       * This should be 0 (default value) when bid_result is not "BID".
       * </pre>
       *
       * <code>optional int32 bid_price = 6;</code>
       */
      public Builder clearBidPrice() {
        
        bidPrice_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bidServer_ = "";
      /**
       * <pre>
       * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
       * we may want to know which bid server caused such corrupted data.
       * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
       * </pre>
       *
       * <code>optional string bid_server = 7;</code>
       */
      public java.lang.String getBidServer() {
        java.lang.Object ref = bidServer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bidServer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
       * we may want to know which bid server caused such corrupted data.
       * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
       * </pre>
       *
       * <code>optional string bid_server = 7;</code>
       */
      public com.google.protobuf.ByteString
          getBidServerBytes() {
        java.lang.Object ref = bidServer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidServer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
       * we may want to know which bid server caused such corrupted data.
       * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
       * </pre>
       *
       * <code>optional string bid_server = 7;</code>
       */
      public Builder setBidServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bidServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
       * we may want to know which bid server caused such corrupted data.
       * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
       * </pre>
       *
       * <code>optional string bid_server = 7;</code>
       */
      public Builder clearBidServer() {
        
        bidServer_ = getDefaultInstance().getBidServer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * In case of corrupted data or abnormal latency (based on received_at &amp; processed_at),
       * we may want to know which bid server caused such corrupted data.
       * This field stores the name/ID of our bid server (responsible for a specific BidLog message).
       * </pre>
       *
       * <code>optional string bid_server = 7;</code>
       */
      public Builder setBidServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bidServer_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.usfca.protobuf.BidLog)
    }

    // @@protoc_insertion_point(class_scope:edu.usfca.protobuf.BidLog)
    private static final edu.usfca.protobuf.Bid.BidLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.protobuf.Bid.BidLog();
    }

    public static edu.usfca.protobuf.Bid.BidLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BidLog>
        PARSER = new com.google.protobuf.AbstractParser<BidLog>() {
      public BidLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BidLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BidLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BidLog> getParserForType() {
      return PARSER;
    }

    public edu.usfca.protobuf.Bid.BidLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_BidLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_BidLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbid.proto\022\022edu.usfca.protobuf\032\024vendor/" +
      "openrtb.proto\"\320\002\n\006BidLog\0223\n\013bid_request\030" +
      "\001 \001(\0132\036.com.google.openrtb.BidRequest\022.\n" +
      "\010exchange\030\002 \001(\0162\034.edu.usfca.protobuf.Exc" +
      "hange\022\023\n\013received_at\030\003 \001(\003\022\024\n\014processed_" +
      "at\030\004 \001(\003\0228\n\nbid_result\030\005 \001(\0162$.edu.usfca" +
      ".protobuf.BidLog.BidResult\022\021\n\tbid_price\030" +
      "\006 \001(\005\022\022\n\nbid_server\030\007 \001(\t\"O\n\tBidResult\022\022" +
      "\n\016UNKNOWN_RESULT\020\000\022\007\n\003BID\020\001\022\020\n\014NO_CANDID" +
      "ATE\020\002\022\023\n\017INVALID_REQUEST\020\003J\004\010\010\020e*\225\001\n\010Exc",
      "hange\022\024\n\020UNKNOWN_EXCHANGE\020\000\022\007\n\003ADX\020\001\022\t\n\005" +
      "MOPUB\020\002\022\t\n\005UNITY\020\003\022\t\n\005OPENX\020\004\022\n\n\006VUNGLE\020" +
      "\005\022\n\n\006INMOBI\020\006\022\t\n\005FYBER\020\007\022\014\n\010APPLOVIN\020\010\022\014" +
      "\n\010ADCOLONY\020\t\022\n\n\006SMAATO\020\nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.openrtb.OpenRtb.getDescriptor(),
        }, assigner);
    internal_static_edu_usfca_protobuf_BidLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_usfca_protobuf_BidLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_BidLog_descriptor,
        new java.lang.String[] { "BidRequest", "Exchange", "ReceivedAt", "ProcessedAt", "BidResult", "BidPrice", "BidServer", });
    com.google.openrtb.OpenRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
