// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package edu.usfca.protobuf;

public final class Profile {
  private Profile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExchangeProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:edu.usfca.protobuf.ExchangeProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
     */
    int getExchangeValue();
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
     */
    edu.usfca.protobuf.Bid.Exchange getExchange();

    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */
    int getCountPerBidResultCount();
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */
    boolean containsCountPerBidResult(
        int key);
    /**
     * Use {@link #getCountPerBidResultMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getCountPerBidResult();
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getCountPerBidResultMap();
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    int getCountPerBidResultOrDefault(
        int key,
        int defaultValue);
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    int getCountPerBidResultOrThrow(
        int key);

    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */
    int getTotalBidPricePerBidResultCount();
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */
    boolean containsTotalBidPricePerBidResult(
        int key);
    /**
     * Use {@link #getTotalBidPricePerBidResultMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Long>
    getTotalBidPricePerBidResult();
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Long>
    getTotalBidPricePerBidResultMap();
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    long getTotalBidPricePerBidResultOrDefault(
        int key,
        long defaultValue);
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    long getTotalBidPricePerBidResultOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code edu.usfca.protobuf.ExchangeProfile}
   */
  public  static final class ExchangeProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:edu.usfca.protobuf.ExchangeProfile)
      ExchangeProfileOrBuilder {
    // Use ExchangeProfile.newBuilder() to construct.
    private ExchangeProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExchangeProfile() {
      exchange_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ExchangeProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              exchange_ = rawValue;
              break;
            }
            case 810: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                countPerBidResult_ = com.google.protobuf.MapField.newMapField(
                    CountPerBidResultDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              countPerBidResult = input.readMessage(
                  CountPerBidResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              countPerBidResult_.getMutableMap().put(countPerBidResult.getKey(), countPerBidResult.getValue());
              break;
            }
            case 8010: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                totalBidPricePerBidResult_ = com.google.protobuf.MapField.newMapField(
                    TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
              totalBidPricePerBidResult = input.readMessage(
                  TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              totalBidPricePerBidResult_.getMutableMap().put(totalBidPricePerBidResult.getKey(), totalBidPricePerBidResult.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 101:
          return internalGetCountPerBidResult();
        case 1001:
          return internalGetTotalBidPricePerBidResult();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.usfca.protobuf.Profile.ExchangeProfile.class, edu.usfca.protobuf.Profile.ExchangeProfile.Builder.class);
    }

    private int bitField0_;
    public static final int EXCHANGE_FIELD_NUMBER = 1;
    private int exchange_;
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
     */
    public int getExchangeValue() {
      return exchange_;
    }
    /**
     * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
     */
    public edu.usfca.protobuf.Bid.Exchange getExchange() {
      edu.usfca.protobuf.Bid.Exchange result = edu.usfca.protobuf.Bid.Exchange.valueOf(exchange_);
      return result == null ? edu.usfca.protobuf.Bid.Exchange.UNRECOGNIZED : result;
    }

    public static final int COUNT_PER_BID_RESULT_FIELD_NUMBER = 101;
    private static final class CountPerBidResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> countPerBidResult_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetCountPerBidResult() {
      if (countPerBidResult_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CountPerBidResultDefaultEntryHolder.defaultEntry);
      }
      return countPerBidResult_;
    }

    public int getCountPerBidResultCount() {
      return internalGetCountPerBidResult().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    public boolean containsCountPerBidResult(
        int key) {
      
      return internalGetCountPerBidResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCountPerBidResultMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getCountPerBidResult() {
      return getCountPerBidResultMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getCountPerBidResultMap() {
      return internalGetCountPerBidResult().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    public int getCountPerBidResultOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetCountPerBidResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
     */

    public int getCountPerBidResultOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetCountPerBidResult().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TOTAL_BID_PRICE_PER_BID_RESULT_FIELD_NUMBER = 1001;
    private static final class TotalBidPricePerBidResultDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Long>newDefaultInstance(
                  edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Long> totalBidPricePerBidResult_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
    internalGetTotalBidPricePerBidResult() {
      if (totalBidPricePerBidResult_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry);
      }
      return totalBidPricePerBidResult_;
    }

    public int getTotalBidPricePerBidResultCount() {
      return internalGetTotalBidPricePerBidResult().getMap().size();
    }
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    public boolean containsTotalBidPricePerBidResult(
        int key) {
      
      return internalGetTotalBidPricePerBidResult().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTotalBidPricePerBidResultMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Long> getTotalBidPricePerBidResult() {
      return getTotalBidPricePerBidResultMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Long> getTotalBidPricePerBidResultMap() {
      return internalGetTotalBidPricePerBidResult().getMap();
    }
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    public long getTotalBidPricePerBidResultOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetTotalBidPricePerBidResult().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
     */

    public long getTotalBidPricePerBidResultOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Long> map =
          internalGetTotalBidPricePerBidResult().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (exchange_ != edu.usfca.protobuf.Bid.Exchange.UNKNOWN_EXCHANGE.getNumber()) {
        output.writeEnum(1, exchange_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetCountPerBidResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        countPerBidResult = CountPerBidResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(101, countPerBidResult);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetTotalBidPricePerBidResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        totalBidPricePerBidResult = TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1001, totalBidPricePerBidResult);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (exchange_ != edu.usfca.protobuf.Bid.Exchange.UNKNOWN_EXCHANGE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, exchange_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetCountPerBidResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        countPerBidResult = CountPerBidResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(101, countPerBidResult);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Long> entry
           : internalGetTotalBidPricePerBidResult().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Long>
        totalBidPricePerBidResult = TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1001, totalBidPricePerBidResult);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.usfca.protobuf.Profile.ExchangeProfile)) {
        return super.equals(obj);
      }
      edu.usfca.protobuf.Profile.ExchangeProfile other = (edu.usfca.protobuf.Profile.ExchangeProfile) obj;

      boolean result = true;
      result = result && exchange_ == other.exchange_;
      result = result && internalGetCountPerBidResult().equals(
          other.internalGetCountPerBidResult());
      result = result && internalGetTotalBidPricePerBidResult().equals(
          other.internalGetTotalBidPricePerBidResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + exchange_;
      if (!internalGetCountPerBidResult().getMap().isEmpty()) {
        hash = (37 * hash) + COUNT_PER_BID_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCountPerBidResult().hashCode();
      }
      if (!internalGetTotalBidPricePerBidResult().getMap().isEmpty()) {
        hash = (37 * hash) + TOTAL_BID_PRICE_PER_BID_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTotalBidPricePerBidResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.usfca.protobuf.Profile.ExchangeProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.usfca.protobuf.Profile.ExchangeProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code edu.usfca.protobuf.ExchangeProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:edu.usfca.protobuf.ExchangeProfile)
        edu.usfca.protobuf.Profile.ExchangeProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 101:
            return internalGetCountPerBidResult();
          case 1001:
            return internalGetTotalBidPricePerBidResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 101:
            return internalGetMutableCountPerBidResult();
          case 1001:
            return internalGetMutableTotalBidPricePerBidResult();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.usfca.protobuf.Profile.ExchangeProfile.class, edu.usfca.protobuf.Profile.ExchangeProfile.Builder.class);
      }

      // Construct using edu.usfca.protobuf.Profile.ExchangeProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        exchange_ = 0;

        internalGetMutableCountPerBidResult().clear();
        internalGetMutableTotalBidPricePerBidResult().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.usfca.protobuf.Profile.internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor;
      }

      public edu.usfca.protobuf.Profile.ExchangeProfile getDefaultInstanceForType() {
        return edu.usfca.protobuf.Profile.ExchangeProfile.getDefaultInstance();
      }

      public edu.usfca.protobuf.Profile.ExchangeProfile build() {
        edu.usfca.protobuf.Profile.ExchangeProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.usfca.protobuf.Profile.ExchangeProfile buildPartial() {
        edu.usfca.protobuf.Profile.ExchangeProfile result = new edu.usfca.protobuf.Profile.ExchangeProfile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.exchange_ = exchange_;
        result.countPerBidResult_ = internalGetCountPerBidResult();
        result.countPerBidResult_.makeImmutable();
        result.totalBidPricePerBidResult_ = internalGetTotalBidPricePerBidResult();
        result.totalBidPricePerBidResult_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.usfca.protobuf.Profile.ExchangeProfile) {
          return mergeFrom((edu.usfca.protobuf.Profile.ExchangeProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.usfca.protobuf.Profile.ExchangeProfile other) {
        if (other == edu.usfca.protobuf.Profile.ExchangeProfile.getDefaultInstance()) return this;
        if (other.exchange_ != 0) {
          setExchangeValue(other.getExchangeValue());
        }
        internalGetMutableCountPerBidResult().mergeFrom(
            other.internalGetCountPerBidResult());
        internalGetMutableTotalBidPricePerBidResult().mergeFrom(
            other.internalGetTotalBidPricePerBidResult());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.usfca.protobuf.Profile.ExchangeProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.usfca.protobuf.Profile.ExchangeProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int exchange_ = 0;
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
       */
      public int getExchangeValue() {
        return exchange_;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
       */
      public Builder setExchangeValue(int value) {
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
       */
      public edu.usfca.protobuf.Bid.Exchange getExchange() {
        edu.usfca.protobuf.Bid.Exchange result = edu.usfca.protobuf.Bid.Exchange.valueOf(exchange_);
        return result == null ? edu.usfca.protobuf.Bid.Exchange.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
       */
      public Builder setExchange(edu.usfca.protobuf.Bid.Exchange value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        exchange_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .edu.usfca.protobuf.Exchange exchange = 1;</code>
       */
      public Builder clearExchange() {
        
        exchange_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> countPerBidResult_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetCountPerBidResult() {
        if (countPerBidResult_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CountPerBidResultDefaultEntryHolder.defaultEntry);
        }
        return countPerBidResult_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetMutableCountPerBidResult() {
        onChanged();;
        if (countPerBidResult_ == null) {
          countPerBidResult_ = com.google.protobuf.MapField.newMapField(
              CountPerBidResultDefaultEntryHolder.defaultEntry);
        }
        if (!countPerBidResult_.isMutable()) {
          countPerBidResult_ = countPerBidResult_.copy();
        }
        return countPerBidResult_;
      }

      public int getCountPerBidResultCount() {
        return internalGetCountPerBidResult().getMap().size();
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public boolean containsCountPerBidResult(
          int key) {
        
        return internalGetCountPerBidResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCountPerBidResultMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer> getCountPerBidResult() {
        return getCountPerBidResultMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Integer> getCountPerBidResultMap() {
        return internalGetCountPerBidResult().getMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public int getCountPerBidResultOrDefault(
          int key,
          int defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetCountPerBidResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public int getCountPerBidResultOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetCountPerBidResult().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCountPerBidResult() {
        getMutableCountPerBidResult().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public Builder removeCountPerBidResult(
          int key) {
        
        getMutableCountPerBidResult().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer>
      getMutableCountPerBidResult() {
        return internalGetMutableCountPerBidResult().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */
      public Builder putCountPerBidResult(
          int key,
          int value) {
        
        
        getMutableCountPerBidResult().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int32&gt; count_per_bid_result = 101;</code>
       */

      public Builder putAllCountPerBidResult(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        getMutableCountPerBidResult().putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Long> totalBidPricePerBidResult_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetTotalBidPricePerBidResult() {
        if (totalBidPricePerBidResult_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry);
        }
        return totalBidPricePerBidResult_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Long>
      internalGetMutableTotalBidPricePerBidResult() {
        onChanged();;
        if (totalBidPricePerBidResult_ == null) {
          totalBidPricePerBidResult_ = com.google.protobuf.MapField.newMapField(
              TotalBidPricePerBidResultDefaultEntryHolder.defaultEntry);
        }
        if (!totalBidPricePerBidResult_.isMutable()) {
          totalBidPricePerBidResult_ = totalBidPricePerBidResult_.copy();
        }
        return totalBidPricePerBidResult_;
      }

      public int getTotalBidPricePerBidResultCount() {
        return internalGetTotalBidPricePerBidResult().getMap().size();
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public boolean containsTotalBidPricePerBidResult(
          int key) {
        
        return internalGetTotalBidPricePerBidResult().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTotalBidPricePerBidResultMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long> getTotalBidPricePerBidResult() {
        return getTotalBidPricePerBidResultMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Long> getTotalBidPricePerBidResultMap() {
        return internalGetTotalBidPricePerBidResult().getMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public long getTotalBidPricePerBidResultOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetTotalBidPricePerBidResult().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public long getTotalBidPricePerBidResultOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Long> map =
            internalGetTotalBidPricePerBidResult().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTotalBidPricePerBidResult() {
        getMutableTotalBidPricePerBidResult().clear();
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public Builder removeTotalBidPricePerBidResult(
          int key) {
        
        getMutableTotalBidPricePerBidResult().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Long>
      getMutableTotalBidPricePerBidResult() {
        return internalGetMutableTotalBidPricePerBidResult().getMutableMap();
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */
      public Builder putTotalBidPricePerBidResult(
          int key,
          long value) {
        
        
        getMutableTotalBidPricePerBidResult().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, int64&gt; total_bid_price_per_bid_result = 1001;</code>
       */

      public Builder putAllTotalBidPricePerBidResult(
          java.util.Map<java.lang.Integer, java.lang.Long> values) {
        getMutableTotalBidPricePerBidResult().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:edu.usfca.protobuf.ExchangeProfile)
    }

    // @@protoc_insertion_point(class_scope:edu.usfca.protobuf.ExchangeProfile)
    private static final edu.usfca.protobuf.Profile.ExchangeProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.usfca.protobuf.Profile.ExchangeProfile();
    }

    public static edu.usfca.protobuf.Profile.ExchangeProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExchangeProfile>
        PARSER = new com.google.protobuf.AbstractParser<ExchangeProfile>() {
      public ExchangeProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExchangeProfile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExchangeProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExchangeProfile> getParserForType() {
      return PARSER;
    }

    public edu.usfca.protobuf.Profile.ExchangeProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_ExchangeProfile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprofile.proto\022\022edu.usfca.protobuf\032\tbid" +
      ".proto\"\231\003\n\017ExchangeProfile\022.\n\010exchange\030\001" +
      " \001(\0162\034.edu.usfca.protobuf.Exchange\022X\n\024co" +
      "unt_per_bid_result\030e \003(\0132:.edu.usfca.pro" +
      "tobuf.ExchangeProfile.CountPerBidResultE" +
      "ntry\022k\n\036total_bid_price_per_bid_result\030\351" +
      "\007 \003(\0132B.edu.usfca.protobuf.ExchangeProfi" +
      "le.TotalBidPricePerBidResultEntry\0328\n\026Cou" +
      "ntPerBidResultEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005valu" +
      "e\030\002 \001(\005:\0028\001\032@\n\036TotalBidPricePerBidResult",
      "Entry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\003:\0028\001J\004\010" +
      "\002\020eJ\005\010f\020\351\007J\006\010\352\007\020\221Nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.usfca.protobuf.Bid.getDescriptor(),
        }, assigner);
    internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_edu_usfca_protobuf_ExchangeProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor,
        new java.lang.String[] { "Exchange", "CountPerBidResult", "TotalBidPricePerBidResult", });
    internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_descriptor =
      internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor.getNestedTypes().get(0);
    internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_ExchangeProfile_CountPerBidResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_descriptor =
      internal_static_edu_usfca_protobuf_ExchangeProfile_descriptor.getNestedTypes().get(1);
    internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_edu_usfca_protobuf_ExchangeProfile_TotalBidPricePerBidResultEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    edu.usfca.protobuf.Bid.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
